[package]
name = "temporalio-sdk-aws-lambda"
version = "0.1.0"
edition = "2024"
authors = ["Temporal Technologies Inc. <sdk@temporal.io>"]
license-file = { workspace = true }
description = "AWS Lambda integration for the Temporal Rust SDK"
homepage = "https://temporal.io/"
repository = "https://github.com/temporalio/sdk-rust"
keywords = ["temporal", "workflow", "aws", "lambda", "serverless"]
categories = ["development-tools"]
readme = "README.md"

[features]
default = []
otel = [
  "dep:opentelemetry",
  "dep:opentelemetry-otlp",
  "dep:opentelemetry_sdk",
  "dep:tracing-opentelemetry",
  "dep:tracing-subscriber",
  "temporalio-common/otel",
  "temporalio-sdk/otel",
]

[dependencies]
anyhow = "1.0"
lambda_runtime = "1.3"
opentelemetry = { workspace = true, features = ["trace"], optional = true }
opentelemetry-otlp = { version = "0.32", default-features = false, features = [
  "grpc-tonic",
  "tokio",
  "trace",
], optional = true }
opentelemetry_sdk = { version = "0.32", default-features = false, features = [
  "rt-tokio",
  "trace",
], optional = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { version = "1.47", default-features = false, features = ["sync", "time"] }
tracing = "0.1"
tracing-opentelemetry = { version = "0.33", optional = true }
tracing-subscriber = { version = "0.3", default-features = false, features = [
  "registry",
], optional = true }

[dependencies.temporalio-client]
path = "../client"
version = "0.7"
default-features = false
features = ["envconfig", "tls-ring"]

[dependencies.temporalio-common]
path = "../common"
version = "0.7"
default-features = false

[dependencies.temporalio-sdk]
path = "../sdk"
version = "0.7"
default-features = false
features = ["envconfig"]

[dev-dependencies]
tempfile = "3"
tokio = { version = "1.47", default-features = false, features = [
  "macros",
  "rt",
  "sync",
  "test-util",
  "time",
] }

[lints]
workspace = true
