name: Heavy Tests

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    permissions:
      contents: read
    timeout-minutes: 20
    runs-on: ubuntu-latest-16-cores
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup
        with:
          mise-install-args: protoc
      - run: cargo integ-test -c "--release" -t heavy_tests -- --test-threads 1
